import React from 'react';
import { Image, Type, Code } from 'lucide-react';

export default function ExampleGallery() {
  const examples = [
    {
      id: 1,
      type: 'image',
      title: 'Vibrant Sci-Fi Cityscape',
      description: 'A futuristic city at sunset, rendered with incredible detail and dynamic lighting.',
      src: 'https://via.placeholder.com/400x300/60a5fa/ffffff?text=AI+City',
      icon: Image
    },
    {
      id: 2,
      type: 'text',
      title: 'Marketing Campaign Slogan',
      description: '"CognitoFlow: Ignite Your Ideas, Automate Your Brilliance." A punchy, memorable slogan.',
      src: '', // No image for text examples
      icon: Type
    },
    {
      id: 3,
      type: 'code',
      title: 'Python Function for Data Processing',
      description: 'A clean and optimized Python function to parse JSON data into a pandas DataFrame.',
      src: '', // No image for code examples
      icon: Code
    },
    {
      id: 4,
      type: 'image',
      title: 'Abstract Art Piece',
      description: 'A harmonious blend of geometric shapes and fluid colors, evoking deep emotion.',
      src: 'https://via.placeholder.com/400x300/8b5cf6/ffffff?text=AI+Abstract',
      icon: Image
    },
    {
      id: 5,
      type: 'text',
      title: 'Blog Post Outline',
      description: 'Detailed outline for a blog post on "The Future of AI in Creative Industries." Sections, sub-points, and keywords included.',
      src: '',
      icon: Type
    },
    {
      id: 6,
      type: 'code',
      title: 'React Component Snippet',
      description: 'A functional React component for a customizable button with various states.',
      src: '',
      icon: Code
    },
  ];

  return (
    <section id="examples" className="py-16 lg:py-24 bg-zinc-900 relative">
      <div className="container mx-auto px-4">
        <h2 className="text-4xl lg:text-5xl font-extrabold text-center text-gray-50 mb-6">
          See What You Can Create
        </h2>
        <p className="text-xl text-center text-gray-300 max-w-3xl mx-auto mb-16">
          Explore a curated selection of content generated by CognitoFlow. From stunning visuals to compelling text and efficient code, the possibilities are limitless.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {examples.map((example) => (
            <div key={example.id} className="group relative bg-zinc-800 bg-opacity-50 border border-zinc-700/60 rounded-2xl overflow-hidden shadow-xl transform hover:scale-[1.02] transition-all duration-300 glassmorphism">
              {example.src && (
                <img src={example.src} alt={example.title} className="w-full h-48 object-cover object-center" />
              )}
              <div className="p-6 flex flex-col h-full">
                <div className="flex items-center text-blue-400 mb-3">
                  <example.icon size={20} className="mr-2" />
                  <span className="font-medium text-lg">{example.type.charAt(0).toUpperCase() + example.type.slice(1)} Generation</span>
                </div>
                <h3 className="text-2xl font-semibold text-gray-50 mb-3 leading-tight">{example.title}</h3>
                <p className="text-gray-300 flex-grow text-base">{example.description}</p>
                <button className="mt-4 self-start px-5 py-2 bg-blue-400 text-white rounded-full text-sm font-medium hover:opacity-90 transition-all duration-200 cursor-pointer">
                  View Full Example
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}