import React from 'react';
import { Eye, Heart, Share2 } from 'lucide-react';

export default function UserGallery() {
  const galleryItems = [
    {
      id: 1, img: 'https://source.unsplash.com/random/400x300/?abstract-neon-city,ai-art', title: 'Neon Dreamscape',
      author: 'AetherArtist', likes: 124, views: '2.1K'
    },
    {
      id: 2, img: 'https://source.unsplash.com/random/400x300/?fantasy-forest,ai-art', title: 'Enchanted Glade',
      author: 'PixelPaladin', likes: 98, views: '1.8K'
    },
    {
      id: 3, img: 'https://source.unsplash.com/random/400x300/?sci-fi-robot,ai-art', title: 'Sentinel Droid',
      author: 'CodeCanvas', likes: 156, views: '2.5K'
    },
    {
      id: 4, img: 'https://source.unsplash.com/random/400x300/?ocean-wave-surreal,ai-art', title: 'Cosmic Wave',
      author: 'SynthSculptor', likes: 210, views: '3.4K'
    },
    {
      id: 5, img: 'https://source.unsplash.com/random/400x300/?steampunk-airship,ai-art', title: 'Sky Sovereign',
      author: 'DreamForge', likes: 88, views: '1.5K'
    },
    {
      id: 6, img: 'https://source.unsplash.com/random/400x300/?ancient-ruins-jungle,ai-art', title: 'Lost Civilization',
      author: 'VoxelVanguard', likes: 192, views: '2.9K'
    },
  ];

  return (
    <section id="gallery" className="py-20 px-4 md:px-8 lg:px-16 max-w-screen-xl mx-auto">
      <div className="text-center mb-16">
        <h2 className="text-4xl md:text-5xl font-bold text-gray-50 mb-4 font-space-grotesk">Community Masterpieces</h2>
        <p className="text-lg text-gray-300 font-inter max-w-3xl mx-auto">Explore a curated collection of stunning visuals generated by the SynthAI community, showcasing the endless possibilities of intelligent creativity.</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {galleryItems.map((item) => (
          <div
            key={item.id}
            className="relative group backdrop-blur-lg bg-white/10 border border-white/20 rounded-xl overflow-hidden shadow-lg hover:shadow-blue-500/30 transition-shadow duration-300"
          >
            <img
              src={item.img}
              alt={item.title}
              className="w-full h-60 object-cover transform group-hover:scale-105 transition-transform duration-300"
            />
            <div className="p-4 relative z-10">
              <h3 className="text-xl font-semibold text-gray-50 mb-1 font-space-grotesk">{item.title}</h3>
              <p className="text-gray-400 text-sm font-inter">By {item.author}</p>
            </div>

            {/* Hover-reveal overlay */}
            <div className="absolute inset-0 bg-black/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              <div className="flex flex-col items-center text-white space-y-3">
                <h3 className="text-2xl font-bold font-space-grotesk text-blue-300">{item.title}</h3>
                <p className="text-md font-inter">@{item.author}</p>
                <div className="flex space-x-4 mt-2">
                  <span className="flex items-center text-sm">
                    <Heart size={16} className="mr-1 text-red-400" /> {item.likes}
                  </span>
                  <span className="flex items-center text-sm">
                    <Eye size={16} className="mr-1 text-blue-400" /> {item.views}
                  </span>
                </div>
                <div className="flex space-x-4 mt-4">
                  <button className="p-2 bg-blue-500 text-white rounded-full hover:opacity-90 transition-all duration-200 cursor-pointer">
                    <Heart size={20} />
                  </button>
                  <button className="p-2 bg-white/20 text-white rounded-full hover:opacity-90 transition-all duration-200 cursor-pointer">
                    <Share2 size={20} />
                  </button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}