import React, { useState } from 'react';
import { HelpCircle, ChevronDown } from 'lucide-react';

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState(0);

  const faqs = [
    {
      question: 'What tech stack does SynapseAI generate?',
      answer: 'SynapseAI outputs clean, modular React JSX components styled with Tailwind CSS utility classes. The code is pure frontend standard, so you can easily drop it into React, Next.js, Vite, Remix, or convert it to pure HTML/CSS.',
    },
    {
      question: 'Do I own the code generated by SynapseAI?',
      answer: 'Yes! 100%. All code generated using SynapseAI belongs entirely to you. There are zero royalties, licenses, or lock-in restrictions.',
    },
    {
      question: 'How does the live prompt iteration work?',
      answer: 'Once a design is generated, you can use the built-in AI chat prompt to request specific modifications—such as "change primary color to dark violet", "add a pricing toggle component", or "make layout 3 columns on desktop".',
    },
    {
      question: 'Is the generated code mobile responsive?',
      answer: 'Absolutely. The AI architecture engine automatically builds responsive flexbox and grid layouts using standard Tailwind breakpoints (`sm:`, `md:`, `lg:`, `xl:`).',
    },
    {
      question: 'Can I import my existing design tokens or colors?',
      answer: 'Yes! You can specify custom color hex codes, font families, or design guidelines directly inside your prompt, and SynapseAI will apply them seamlessly across all generated components.',
    },
  ];

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="relative w-full py-28 px-6 bg-zinc-950/40 border-t border-zinc-900/80 overflow-hidden">
      <div className="relative max-w-4xl mx-auto z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-sky-500/30 bg-sky-500/10 text-sky-300 text-xs font-semibold tracking-wider uppercase mb-6 shadow-[0_0_15px_rgba(56,189,248,0.15)]">
            <HelpCircle size={14} className="text-sky-400" />
            <span>Frequently Asked Questions</span>
          </div>

          <h2 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight leading-tight mb-6">
            Got Questions? <br className="hidden sm:inline" />
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-sky-400 via-indigo-300 to-purple-400">
              We Have Answers
            </span>
          </h2>

          <p className="text-zinc-400 text-lg leading-relaxed">
            Everything you need to know about SynapseAI, code generation, and export capabilities.
          </p>
        </div>

        {/* Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className={`rounded-2xl border transition-all duration-300 overflow-hidden ${
                  isOpen
                    ? 'border-sky-500/40 bg-zinc-900/90 shadow-[0_0_20px_rgba(56,189,248,0.1)]'
                    : 'border-zinc-800/80 bg-zinc-900/40 hover:border-zinc-700'
                }`}
              >
                <button
                  onClick={() => toggleFAQ(idx)}
                  className="w-full p-6 text-left flex items-center justify-between gap-4 font-bold text-base md:text-lg text-white hover:text-sky-300 transition-colors"
                >
                  <span>{faq.question}</span>
                  <div className={`p-2 rounded-lg bg-zinc-800/80 text-zinc-300 shrink-0 transition-transform duration-300 ${isOpen ? 'rotate-180 bg-sky-500 text-black' : ''}`}>
                    <ChevronDown size={18} />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-6 pb-6 text-sm md:text-base text-zinc-400 leading-relaxed border-t border-zinc-800/60 pt-4 animate-fade-in">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
